version: 2
jobs:
  build:
    docker: 
      - image: gcc:8
    steps:
      - checkout 
      - run: make
      - run: make test
      - run: mkdir build && cd build && cmake .. && make  && make test
